language: node_js
node_js:
- '7'
before_script: gulp hint
notifications:
  webhooks:
    urls:
      - https://pppbackend.herokuapp.com/travishook
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_error: always # default: always
after_script: cat "https://s3.amazonaws.com/archive.travis-ci.org/jobs/235870795/log.txt?X-Amz-Expires=30&X-Amz-Date=20170525T012658Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJRYRXRSVGNKPKO5A/20170525/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=08362acdaee237abea9ef59b3b032a74e0a95592150e011a860443c899fd7322"> file.txt
deploy:
  provider: heroku
  api_key:
    secure: fdISwaJEb3r7TVwuwlLxdFBDWKbn/+HuQNH3JLtQhf8K8eOD1ud0ERdSs5dQnp91Z8QXytNZWe+eb+bSri2BytLw4OHcoVBUsXlqAf8YrffzdxFQw3k16Z6FoelR0oBbJf/QUXNabwA1zCw/bDCtTfxgbcq6DKbVw1rIUxgsfpJhTxaW4Hj9DGnAKo9EW6Z6Kkts77UxuO8O3Xu+xf4+Li48sXC3RZJXyFuUuK6pWqNGg9IZAhUk1hj+kBnzygmgw5fR5lFVJVOyDU/yCSogelOrFSlDiPe0DLjhjSGV22LMZGecLmqzqiCXrbtmsCOdwB6hplCa+vCr7rSRRAQIBiHFkGYqR60b6No1qHR2w53Iio6nap/IPgyT0MJZm6kkIUu1z+h3RiiZpmrS09OqlPjgLb2HWzCqfylurqnBm4dkMY2fC7Qwe+JVZv9wkdfk4480g3fCawud7jTDrCtgQ9bnBplqVHi27xpl0v8lT4WZk0mubCuJItkYfuFQvlVLx9sxGQMhq0QH551ecFUXfh5WPh3UrwBOlTP9zz79TplXCxBdfutzJSmm8cKvuPMgImXhTTMPsSvbhBlS8ghGDNOmGWOOIUG5SxPo3vnfvmH/Bw7fXJ7ZIDyE1PQEjNEd/oFdzdTr/2STGMK/z3Xf33w3stdIBUHMhCgReRt5N+8=
  app: testsana
  on:
    repo: sanasa/Angular2_expressjs_mongodb_starter
